/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odev1;
import java.util.ArrayList;
import java.util.Arrays;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
   
    @Test
   public void testFound() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 8, 3, 6));
      assertTrue(App.search(array, 4, 2));
    }
    public void testFound2() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(24, 35, 34, 65));
        assertTrue(App.search(array, 7, 5));
    }
  
    @Test
    public void testNotFound() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(2, 6, 8, 4));
      assertFalse(App.search(array, 5, 2));
    }

    @Test
    public void testNotFound2() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(10, 11, 12, 14));
      assertFalse(App.search(array, 3, 5));
    }


    @Test
    public void testEmptyArray() {
      ArrayList<Integer> array = new ArrayList<>();
      assertFalse(App.search(array, 1, 4));
    }

    @Test
    public void testNull() {
      assertFalse(App.search(null, 1, 5));
    }

}
